### ISSUE TITLE
Not Found for url: http+docker://localhost/v1.43/containers/sweagent-swe-agent-latest-22ea25e377/json

### ISSUE THREAD

**Issue by yuanzhixiang** [princeton-nlp/SWE-agent#110]
### Describe the bug

How to fix below problem?

```
DEBUG    Starting container with command: docker run -i --rm --name sweagent-swe-agent-latest-22ea25e377 sweagent/swe-agent:latest /bin/bash -l -m                                                                                                           
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/containers/sweagent-swe-agent-latest-22ea25e377/json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/run.py", line 288, in <module>
    main(args)
  File "/app/run.py", line 90, in main
    env = SWEEnv(args.environment)
  File "/app/sweagent/environment/swe_env.py", line 107, in __init__
    self._reset_container()
  File "/app/sweagent/environment/swe_env.py", line 355, in _reset_container
    self._init_container()
  File "/app/sweagent/environment/swe_env.py", line 388, in _init_container
    self.container_obj = client.containers.get(self.container_name)
  File "/usr/local/lib/python3.9/site-packages/docker/models/containers.py", line 951, in get
    resp = self.client.api.inspect_container(container_id)
  File "/usr/local/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/docker/api/container.py", line 792, in inspect_container
    return self._result(
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.43/containers/sweagent-swe-agent-latest-22ea25e377/json: Not Found ("No such container: sweagent-swe-agent-latest-22ea25e377")
```

### Steps/Code to Reproduce

docker command run

### Expected Results

No error

### Actual Results

Error

**Comment by klieret** [comment]
Are you on the latest version? What command did you run? Can you try passing in `--image_name=sweagent/swe-agent:latest`?

This might happen if you created the docker images with `./setup.sh` a while ago and now pulled the latest version from the repo.

**Comment by yuanzhixiang** [comment]
> Are you on the latest version? What command did you run? Can you try passing in `--image_name=sweagent/swe-agent:latest`?
> 
> This might happen if you created the docker images with `./setup.sh` a while ago and now pulled the latest version from the repo.

I using docker run this project and using sweagent/swe-agent-run:latest image. I just deleted the image and pulled it again but I still have this problem.

**Comment by klieret** [comment]
Can you copy the command that you were running?

**Comment by klieret** [comment]
You were probably skipping over one step from the instructions. You need to run

```bash
docker pull sweagent/swe-agent:latest
```

once

**Comment by yuanzhixiang** [comment]
> You were probably skipping over one step from the instructions. You need to run
> 
> ```shell
> docker pull sweagent/swe-agent:latest
> ```
> 
> once

You are right, thanks!
