### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/app/keys.cfg'

### ISSUE THREAD

**Issue by bvandorf** [princeton-nlp/SWE-agent#115]
### Describe the bug

/app/keys.cfg is detected as a directory it looks like 
I have tried with both docker run commands listed here

### Steps/Code to Reproduce

```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
  -v /home/user/scripts/vscode/python/swe_agent/keys.cfg:/app/keys.cfg \
  sweagent/swe-agent-run:latest \
  python run.py --image_name=sweagent/swe-agent:latest \
  --model_name gpt4 \
  --data_path https://github.com/pvlib/pvlib-python/issues/1603 \
  --config_file config/default_from_url.yaml  --skip_existing=False
```
  
```
docker run --rm -it -v //var/run/docker.sock:/var/run/docker.sock \
  -v //home/user/scripts/vscode/python/swe_agent/keys.cfg:/app/keys.cfg \
  sweagent/swe-agent-run:latest \
  python run.py --image_name=sweagent/swe-agent:latest \
  --model_name gpt4 \
  --data_path https://github.com/pvlib/pvlib-python/issues/1603 \
  --config_file config/default_from_url.yaml  --skip_existing=False
```
### Expected Results

Run

### Actual Results
```
Traceback (most recent call last):
  File "/app/run.py", line 288, in <module>
    main(args)
  File "/app/run.py", line 88, in main
    agent = Agent("primary", args.agent)
  File "/app/sweagent/agent/agents.py", line 186, in __init__
    self.model = get_model(args.model, args.config._commands + args.config.subroutine_types)
  File "/app/sweagent/agent/models.py", line 706, in get_model
    return OpenAIModel(args, commands)
  File "/app/sweagent/agent/models.py", line 225, in __init__
    cfg = config.Config(os.path.join(os.getcwd(), "keys.cfg"))
  File "/usr/local/lib/python3.9/site-packages/config/__init__.py", line 707, in __init__
    self.load_file(stream_or_path, kwargs.get('encoding'))
  File "/usr/local/lib/python3.9/site-packages/config/__init__.py", line 815, in load_file
    with io.open(path, encoding=encoding or 'utf-8') as f:
IsADirectoryError: [Errno 21] Is a directory: '/app/keys.cfg'
```
### System Information

Windows 10 WSL
Python 3.10.12
Docker version 24.0.6, build ed223bc

**Comment by klieret** [comment]
Can you double check that the path to `keys.cfg` on the host is correct? If docker doesn't find the file, it will mount an empty directory, I think.

See for example here: https://stackoverflow.com/a/44950494/

**Comment by klieret** [comment]
Feel free to reopen if this didn't address your issue!
