### ISSUE TITLE
Unable to run the docker run command from the readme example

### ISSUE THREAD

**Issue by AyoTheDev** [princeton-nlp/SWE-agent#136]
### Describe the bug

when running the command from readme:

```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
  -v /xxx/keys.cfg:/app/keys.cfg \
  sweagent/swe-agent-run:latest \
  python run.py --image_name=sweagent/swe-agent:latest \
  --model_name gpt4 \
  --data_path https://github.com/pvlib/pvlib-python/issues/1603 \
  --config_file config/default_from_url.yaml  --skip_existing=False
```

I get:

```
INFO     💽 Loaded dataset from https://github.com/pvlib/pvlib-python/issues/1603
DEBUG    Starting container with command: docker run -i --rm --name sweagent-swe-agent-latest-4204cdcba5
         sweagent/swe-agent:latest /bin/bash -l -m
INFO     🌱 Environment Initialized
INFO     ▶️  Beginning task 0
INFO     Trying to clone from non-mirror...
ERROR    Failed to source conda: /bin/bash: line 119: source: /root/miniconda3/etc/profile.d/conda.sh: cannot execute
         binary file

INFO     Beginning environment shutdown...
INFO     Agent container stopped
Traceback (most recent call last):
  File "/app/run.py", line 105, in main
    observation, info = env.reset(index)
  File "/app/sweagent/environment/swe_env.py", line 192, in reset
    self.communicate_with_handling(
  File "/app/sweagent/environment/swe_env.py", line 489, in communicate_with_handling
    raise RuntimeError(f"{error_msg}: {logs}")
RuntimeError: Failed to source conda: /bin/bash: line 119: source: /root/miniconda3/etc/profile.d/conda.sh: cannot execute binary file

WARNING  ❌ Failed on pvlib__pvlib-python-i1603: Failed to source conda: /bin/bash: line 119: source:
         /root/miniconda3/etc/profile.d/conda.sh: cannot execute binary file

INFO     Beginning environment shutdown...
INFO     Agent container stopped
DEBUG    Starting container with command: docker run -i --rm --name sweagent-swe-agent-latest-4204cdcba5
         sweagent/swe-agent:latest /bin/bash -l -m
INFO     🌱 Environment Initialized
```

### Steps/Code to Reproduce

see description above

### Expected Results

the docker run command should run successfully

### Actual Results

ERROR    Failed to source conda: /bin/bash: line 119: source: /root/miniconda3/etc/profile.d/conda.sh: cannot execute
         binary file

### System Information

MacOS, M1.

**Comment by klieret** [comment]
Can you double check that you're on a M1? What's the output of
```
uname -a
```

**Comment by AyoTheDev** [comment]
@klieret 
```
Darwin ayoolas-MacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64
```

Thanks for your reply

**Comment by klieret** [comment]
Very strange. I'm also in a M1 and I can run this command just fine (note that you have to switch out your path to the `keys.cfg`, but that lead to a separate error later).

Just to make sure, can you do 

```bash
docker pull sweagent/swe-agent-run
docker pull sweagent/swe-agent
```

to ensure you're on the latest version?

Then, if things still fail, can you try to inspect the docker image manually:
```bash
 docker run --rm -it sweagent/swe-agent /bin/bash  
```

and now try to 
```bash
# probably gonna fail with same reason
source root/miniconda3/etc/profile.d/conda.sh
```
and collect info
```bash
stat root/miniconda3/etc/profile.d/conda.sh
head root/miniconda3/etc/profile.d/conda.sh
```

**Comment by AyoTheDev** [comment]
@klieret thanks again for your help.

things seem to work correctly after

```
docker pull sweagent/swe-agent-run
docker pull sweagent/swe-agent
```

not sure how I managed to not be on the latest version as I only heard about SWE-agent a few hours ago! thanks again

**Comment by klieret** [comment]
Thanks for closing the issue!
