### ISSUE TITLE
Fixing type hints of non-string dataclass members

### ISSUE THREAD

**Issue by klieret** [princeton-nlp/SWE-agent#178]
In `agents.py` we define dataclasses like such:

```python
@dataclass(frozen=True)
class AgentConfig(FrozenSerializable):
    parse_command: str = "ParseCommandBash"

  def __post_init__(self):
    # need object.__setattr__ because dataclass is frozen
    object.__setattr__(self, "parse_command", ParseCommand.get(self.parse_command)) 
```

executes well, but the VSCode or any static checker won't understand that `parse_command` is a `Callable`.

What I've tried:

```python
    parse_command: ParseCommand = field(
        default=ParseCommandBash(),
        metadata={
            "serialize": lambda command: command.__class__.__name__,
            "deserialize": ParseCommand.get,
        }
    )
```

or simpler

```python
parse_command: ParseCommand = ParseCommandBash()  # type: ignore
```

but both fail with

```
Traceback (most recent call last):
  File "/Users/fuchur/Documents/24/git_sync/SWE-agent/run.py", line 321, in <module>
    args = get_args()
  File "/Users/fuchur/Documents/24/git_sync/SWE-agent/run.py", line 293, in get_args
    agent=AgentArguments(
  File "<string>", line 6, in __init__
  File "/Users/fuchur/Documents/24/git_sync/SWE-agent/sweagent/agent/agents.py", line 197, in __post_init__
    config = AgentConfig.load_yaml(self.config_file)
  File "/opt/miniconda3/envs/swe-agent/lib/python3.9/site-packages/simple_parsing/helpers/serialization/serializable.py", line 357, in load_yaml
    return load_yaml(cls, path, load_fn=load_fn, drop_extra_fields=drop_extra_fields, **kwargs)
  File "/opt/miniconda3/envs/swe-agent/lib/python3.9/site-packages/simple_parsing/helpers/serialization/serializable.py", line 657, in load_yaml
    return load(cls, path, drop_extra_fields=drop_extra_fields, load_fn=partial(load_fn, **kwargs))
  File "/opt/miniconda3/envs/swe-agent/lib/python3.9/site-packages/simple_parsing/helpers/serialization/serializable.py", line 539, in load
    return from_dict(cls, d, drop_extra_fields=drop_extra_fields)
  File "/opt/miniconda3/envs/swe-agent/lib/python3.9/site-packages/simple_parsing/helpers/serialization/serializable.py", line 843, in from_dict
    field_value = decode_field(
  File "/opt/miniconda3/envs/swe-agent/lib/python3.9/site-packages/simple_parsing/helpers/serialization/decoding.py", line 150, in decode_field
    decoded_value = decoding_function(raw_value, drop_extra_fields=drop_extra_fields)
  File "/opt/miniconda3/envs/swe-agent/lib/python3.9/site-packages/simple_parsing/helpers/serialization/serializable.py", line 803, in from_dict
    obj_dict: dict[str, Any] = d.copy()
AttributeError: 'str' object has no attribute 'copy'
```

**Comment by klieret** [comment]
will be part of 1.0.0
