### ISSUE TITLE
Issue with parsing keys.cfg

### ISSUE THREAD

**Issue by Mohinem** [princeton-nlp/SWE-agent#25]
I run this command to check inference of an issue in a private GitHub repo-

`(swe-agent) rasdaman@mohinem-TUF-Gaming-FX505DT-FX505DT:~/SWE-agent$ python run.py --model_name gpt4 --data_path https://github.com/Mohinem/`

and get a TokenizerError with the following console log-                                                                             
                                                                                                     
```
Traceback (most recent call last):
  File "/home/rasdaman/SWE-agent/run.py", line 223, in <module>
    main(args)
  File "/home/rasdaman/SWE-agent/run.py", line 64, in main
    agent = Agent("primary", args.agent)
  File "/home/rasdaman/SWE-agent/sweagent/agent/agents.py", line 186, in __init__
    self.model = get_model(args.model, args.config._commands + args.config.subroutine_types)
  File "/home/rasdaman/SWE-agent/sweagent/agent/models.py", line 684, in get_model
    return OpenAIModel(args, commands)
  File "/home/rasdaman/SWE-agent/sweagent/agent/models.py", line 222, in __init__
    cfg = config.Config(os.path.join(os.getcwd(), "keys.cfg"))
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/__init__.py", line 707, in __init__
    self.load_file(stream_or_path, kwargs.get('encoding'))
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/__init__.py", line 816, in load_file
    self.load(f)
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/__init__.py", line 803, in load
    items = p.container()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 292, in container
    result = self.mapping_body()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 183, in mapping_body
    value = self.expr()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 496, in or_expr
    result = self.and_expr()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 488, in and_expr
    result = self.not_expr()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 481, in not_expr
    result = self.comparison()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 472, in comparison
    result = self.bitor_expr()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 450, in bitor_expr
    result = self.bitxor_expr()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 442, in bitxor_expr
    result = self.bitand_expr()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 434, in bitand_expr
    result = self.shift_expr()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 425, in shift_expr
    result = self.add_expr()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 416, in add_expr
    result = self.mul_expr()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 407, in mul_expr
    result = self.u_expr()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 400, in u_expr
    result = self.power()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 390, in power
    result = self.primary()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 383, in primary
    result = self.atom()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 309, in atom
    result = self.value()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 274, in value
    self.advance()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/parser.py", line 130, in advance
    self.token = self.tokenizer.get_token()
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/tokens.py", line 1154, in get_token
    tt, token, value, endline, endcol = get_number(token)
  File "/home/rasdaman/miniconda3/envs/swe-agent/lib/python3.9/site-packages/config/tokens.py", line 923, in get_number
    raise e
config.tokens.TokenizerError: Invalid character in number: Q
```

I do not understand this log, but chatgpt4 tells me that it's caused because of parsing errors from keys.cfg configuration file. Here is my config-

```
OPENAI_API_KEY: sk-691QbGhoMYXTn9nyXXXXT4BlbHFdl2eYcxxxxB5jKpJ9jJpo
GITHUB_TOKEN: ghp_GTiVuqGTUxHGXXXXJTnAp1Jb70gOH0GXXXX
```

(i have changed the keys of course)

1. Do I need to add quotes to the API keys ?
2. Otherwise, is there anything I could do so that the parsing is correct ?

**Comment by jeffvun** [comment]
Probably an issue with the formatting of the API keys. Few work around : 

Check for Special Characters: Ensure that there are no special characters or unexpected characters in the API keys or any other values in the keys.cfg file. 
Quoting API Keys: While it's generally not required to add quotes around API keys in a configuration file, it's a good practice, especially if the keys contain spaces or other special characters.
Verify Configuration Format: Double-check that the keys.cfg file follows the correct YAML or JSON format.

**Comment by klieret** [comment]
Can you try adding quotation marks around your keys? If you read the error message carefully, you can see that it tries to interpret some string as a number.

**Comment by timothycarambat** [comment]
Your keys need double/single quotes around them

**Comment by klieret** [comment]
Closing. feel free to reopen if issue persists
