### ISSUE TITLE
Is there a way to set up proxy? 

### ISSUE THREAD

**Issue by elifbabaoglu** [princeton-nlp/SWE-agent#260]
### Describe the issue

Is there a way to set up proxy? I am getting access denied because the proxy is not set up

**Comment by klieret** [comment]
Could you elaborate?

**Comment by elifbabaoglu** [comment]
I am running this internally in a restricted access to websites and post get requests. I have to set up my proxy here in run.py, 
def run(self, index):
    # Reset environment
    instance_id = self.env.data[index]["instance_id"]
    os.environ['http_proxy'] = ''
    os.environ['https_proxy'] = ''
    print("Current HTTP_PROXY: ", os.getenv('HTTP_PROXY'))
    proxies = {
        'http': os.getenv('HTTP_PROXY'),
        'https': os.getenv('HTTPS_PROXY'),
    }
    for hook in self.hooks:
        hook.on_instance_start(index=index, instance=self.env.data[index])
    assert isinstance(instance_id, str)  # mypy
    if self.should_skip(instance_id):
        for hook in self.hooks:
            hook.on_instance_skipped()
        raise _ContinueLoop
    logger.info("▶️  Beginning task " + str(index))

    observation, info = self.env.reset(index)
    
    it hasn't worked and i do get this error below
```

Traceback (most recent call last):
  File "/home/ebabaoglu/SWE-AGENT/SWE-agent/run.py", line 511, in <module>
    main(get_args())
  File "/home/ebabaoglu/SWE-AGENT/SWE-agent/run.py", line 507, in main
    Main(args).main()
  File "/home/ebabaoglu/SWE-AGENT/SWE-agent/run.py", line 293, in __init__
    self.env = SWEEnv(args.environment)
  File "/home/ebabaoglu/SWE-AGENT/SWE-agent/sweagent/environment/swe_env.py", line 117, in __init__
    self.data = get_instances(self.data_path, self.args.base_commit, self.args.split, token=self._github_token, repo_path=self.args.repo_path)
  File "/home/ebabaoglu/SWE-AGENT/SWE-agent/sweagent/environment/utils.py", line 597, in get_instances
    ib.set_problem_statement(file_path)
  File "/home/ebabaoglu/SWE-AGENT/SWE-agent/sweagent/environment/utils.py", line 474, in set_problem_statement
    self.set_problem_statement_from_gh_issue(data_path)
  File "/home/ebabaoglu/SWE-AGENT/SWE-agent/sweagent/environment/utils.py", line 460, in set_problem_statement_from_gh_issue
    self.args["problem_statement"] = get_problem_statement_from_github_issue(owner, repo, issue_number, token=self.token)
  File "/home/ebabaoglu/SWE-AGENT/SWE-agent/sweagent/environment/utils.py", line 441, in get_problem_statement_from_github_issue
    issue = api.issues.get(owner, repo, issue_number)
  File "/home/ebabaoglu/miniconda3/envs/swe-agent/lib/python3.9/site-packages/ghapi/core.py", line 62, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/home/ebabaoglu/miniconda3/envs/swe-agent/lib/python3.9/site-packages/ghapi/core.py", line 121, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=debug, return_headers=True,
  File "/home/ebabaoglu/miniconda3/envs/swe-agent/lib/python3.9/site-packages/fastcore/net.py", line 218, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/home/ebabaoglu/miniconda3/envs/swe-agent/lib/python3.9/site-packages/fastcore/net.py", line 117, in urlread
    with urlopen(url, data=data, headers=headers, timeout=timeout, **kwargs) as u: res,hdrs = u.read(),u.headers
  File "/home/ebabaoglu/miniconda3/envs/swe-agent/lib/python3.9/site-packages/fastcore/net.py", line 108, in urlopen
    try: return urlopener().open(urlwrap(url, data=data, headers=headers), timeout=timeout)
  File "/home/ebabaoglu/miniconda3/envs/swe-agent/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/home/ebabaoglu/miniconda3/envs/swe-agent/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/ebabaoglu/miniconda3/envs/swe-agent/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/ebabaoglu/miniconda3/envs/swe-agent/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/ebabaoglu/miniconda3/envs/swe-agent/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Tunnel connection failed: 407 Proxy Authentication Required>
```

**Comment by elifbabaoglu** [comment]
because the call to make an http request doesn't pass in the proxy settings 
from the miniconda library

**Comment by klieret** [comment]
Seems like this is occurring while you're pulling information from github. Can't you just run on a local repo then?

Alternatively, you could check how you can set up the gh API to use proxy settings.

Not sure if we can do much on our side (though if there's a _simple_ thing we could do, let me know or open a PR)
