### ISSUE TITLE
Add Support for Llama 3

### ISSUE THREAD

**Issue by snowsky** [princeton-nlp/SWE-agent#262]
### Describe the feature

The version 3 of Llama is named `llama3:*` now the models of llama start with `ollama:`.

### Potential Solutions

N/A

**Comment by snowsky** [comment]
just took a quick look again, the module name of llama3 is `ollama:llama3:70b`, closing the issue!

**Comment by xaionaro** [comment]
It does not work for me.

```
(SWE-agent) xaionaro@void:~/src/SWE-agent$ python3 ./sweagent/run/run.py run --agent.model.api_base http://127.0.0.1:11434/ --agent.model.name=ollama:llama3:70b --env.repo.github_url=https://github.com/xaionaro-go/streamctl --problem_statement.github_url=https://github.com/xaionaro-go/streamctl/issues/1
 INFO      This is SWE-agent version 1.0.0 (0772c99cb2903ccf22ba543eaf128742afa470d6) with SWE-ReX 1.0.1 ().
🔧 INFO     Loading default config from /home/xaionaro/src/SWE-agent/config/default.yaml, because no other config file is specified. Specify --no_config_file to disable this.
🔧 WARN     demonstration_template is ignored when put_demos_in_history is True
🔧 INFO     Setting problem statement based on github issue url
🔧 INFO     Loaded environment variables from /home/xaionaro/src/SWE-agent/.env
Traceback (most recent call last):
  File "/home/xaionaro/src/SWE-agent/./sweagent/run/run.py", line 116, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/xaionaro/src/SWE-agent/./sweagent/run/run.py", line 81, in main
    run_single_main(remaining_args)
  File "/home/xaionaro/src/SWE-agent/sweagent/run/run_single.py", line 208, in run_from_cli
    run_from_config(BasicCLI(RunSingleConfig, help_text=help_text).get_config(args))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xaionaro/src/SWE-agent/sweagent/run/run_single.py", line 199, in run_from_config
    RunSingle.from_config(config).run()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xaionaro/src/SWE-agent/sweagent/run/run_single.py", line 157, in from_config
    agent = Agent.from_config(config.agent)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xaionaro/src/SWE-agent/sweagent/agent/agents.py", line 191, in from_config
    model = get_model(config.model, config.tools)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xaionaro/src/SWE-agent/sweagent/agent/models.py", line 622, in get_model
    return LiteLLMModel(args, tools)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xaionaro/src/SWE-agent/sweagent/agent/models.py", line 437, in __init__
    raise ValueError(msg)
ValueError: Model ollama:llama3:70b does not support function calling
```
