### ISSUE TITLE
Default `environment.yaml` doesn't install in conda

### ISSUE THREAD

**Issue by ketsapiwiq** [princeton-nlp/SWE-agent#315]
### Describe the bug

Because of `install_configs["python"]` and because of the yaml keys in `environment.yml` we get a conda problem.
We might want to install a default python like:
```
            install_configs["python"] = install_configs.get("python", "3.9")
```

### Steps/commands/code to Reproduce

`python run.py --image_name=sweagent/swe-agent:latest --model_name gpt4  --data_path "./my_issue.md" --repo_path "./" --config_file "config/custom.yaml" --apply_patch_locally --environment_setup="environment.yml"`

### Error message/results

```python
DEBUG    Copying /home/hadrien/git/SWE-agent to container at /__home__hadrien__git__SWE-agent with command: docker cp                 
         /home/hadrien/git/SWE-agent 51de29382e67919a3b95f1d11053f2e5029853143c3eae6745c7723b547fa265:/__home__hadrien__git__SWE-agent
Successfully copied 5.39MB to 51de29382e67919a3b95f1d11053f2e5029853143c3eae6745c7723b547fa265:/__home__hadrien__git__SWE-agent
INFO     __home__hadrien__git__SWE-agent__bab424f conda env not found, creating...                                                    
Traceback (most recent call last):
  File "/home/hadrien/git/SWE-agent/run.py", line 363, in main
    self.run(index)
  File "/home/hadrien/git/SWE-agent/run.py", line 318, in run
    observation, info = self.env.reset(index)
  File "/home/hadrien/git/SWE-agent/sweagent/environment/swe_env.py", line 271, in reset
    self.install_env()
  File "/home/hadrien/git/SWE-agent/sweagent/environment/swe_env.py", line 742, in install_env
    f"conda create -n {env_name} python={install_configs['python']} {packages} -y",
KeyError: 'python'
WARNING  ❌ Failed on 2949d2: 'python'                                                                                                
INFO     Beginning environment shutdown...                                                                                            
INFO     Agent container stopped       DEBUG    Copying /home/hadrien/git/SWE-agent to container at /__home__hadrien__git__SWE-agent with command: docker cp                 
         /home/hadrien/git/SWE-agent 51de29382e67919a3b95f1d11053f2e5029853143c3eae6745c7723b547fa265:/__home__hadrien__git__SWE-agent
Successfully copied 5.39MB to 51de29382e67919a3b95f1d11053f2e5029853143c3eae6745c7723b547fa265:/__home__hadrien__git__SWE-agent
INFO     __home__hadrien__git__SWE-agent__bab424f conda env not found, creating...                                                    
Traceback (most recent call last):
  File "/home/hadrien/git/SWE-agent/run.py", line 363, in main
    self.run(index)
  File "/home/hadrien/git/SWE-agent/run.py", line 318, in run
    observation, info = self.env.reset(index)
  File "/home/hadrien/git/SWE-agent/sweagent/environment/swe_env.py", line 271, in reset
    self.install_env()
  File "/home/hadrien/git/SWE-agent/sweagent/environment/swe_env.py", line 742, in install_env
    f"conda create -n {env_name} python={install_configs['python']} {packages} -y",
KeyError: 'python'
WARNING  ❌ Failed on 2949d2: 'python'                                                                                                
INFO     Beginning environment shutdown...                                                                                            
INFO     Agent container stopped       
```

### System Information

Docker

### Checklist

- [X] I'm running with the latest docker container/on the latest development version
- [X] I've searched the other issues for a duplicate
- [X] I have copied the full command/code that I ran
- [X] I have copied the **full** log file/error message that was the result (if applicable)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
Could you show me the `environment.yml` that you're using?

**Comment by klieret** [comment]
Could you show me what you're passing as `--environment_setup`?

**Comment by ketsapiwiq** [comment]
Oh I see, sorry I didn't understand what we needed to specify. I used it for this file:
```
name: swe-agent
dependencies:
  - python=3.9
  - pip
  - curl
  - pip:
    - -r requirements.txt
    ```
    with the flag mentioned: `--environment_setup="environment.yml"`

**Comment by ketsapiwiq** [comment]
Just found this indeed: https://github.com/princeton-nlp/SWE-agent/pull/153

Syntax should be
```yaml
install: echo 'installing'
packages: pytest
pip_packages: tox
python: '3.6'
```

Got it! Sorry for the noise!

**Comment by ketsapiwiq** [comment]
Just a quick note, due to: https://github.com/princeton-nlp/SWE-agent//blob/3d95f487e8d1ca2c7889434ebfa4c3b23672e48c/sweagent/environment/swe_env.py#L749
It's not `pip_packages: tox` but:
```yaml
pip_packages:
- tox
```
Otherwise it lists them letter by letter (for the case of one pip package).

**Comment by klieret** [comment]
Good point, thanks!
