### ISSUE TITLE
Web UI is not working (./start_web_ui.sh). The Localhost does not opens.

### ISSUE THREAD

**Issue by MAhmadUzair** [princeton-nlp/SWE-agent#389]
### Describe the bug

I am facing difficulty in starting WebUI.

I am following your this documentation = https://princeton-nlp.github.io/SWE-agent/installation/codespaces/#running-the-web-ui

Here's What I am doing.

First I cloned your sweoagent repo and added keys.cfg and simply ran it using ./setup.sh command. Then I paste this command "./start_web_ui.sh" to open WebUI. The session ends right after starting of it. Kindly look at it.

Problem:
uzair@UZAIR:~/project/SWE-agent$ ./start_web_ui.sh

up to date, audited 1819 packages in 9s

349 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (2 moderate, 6 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[PM2] Starting /home/uzair/.nvm/versions/node/v20.13.1/bin/npm in fork_mode (1 instance)
[PM2] Done.
┌────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ swe-agent    │ default     │ 0.39.3  │ fork    │ 22422    │ 0s     │ 0    │ online    │ 0%       │ 16.6mb   │ uzair    │ disabled │
└────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[PM2][WARN] Current process list is not synchronized with saved list. Type 'pm2 save' to synchronize.
* If you are running on your own machine, then a browser window
  should have already opened. If not, wait a few more seconds, then
  open your browser at http://localhost:3000
* If you are running in github codespaces, please click the popup
  that offers to forward port 3000 (not 8000!).
  Missed it? Find more information at
  https://princeton-nlp.github.io/SWE-agent/installation/codespaces#running-the-web-ui
* Something went wrong? Please check
  web_api.log for error messages!
[PM2] Applying action deleteProcessId on app [swe-agent](ids: [ 0 ])
[PM2] [swe-agent](0) ✓
┌────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
└────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
uzair@UZAIR:~/project/SWE-agent$ 

And then when I click localhost:3000, It does not loads the WebUI.

When I check web_api.log (It shows below error)

Traceback (most recent call last):
  File "/home/uzair/project/SWE-agent/sweagent/api/server.py", line 22, in <module>
    from sweagent import CONFIG_DIR, PACKAGE_DIR
ModuleNotFoundError: No module named 'sweagent'

### Steps/commands/code to Reproduce

'''When I check web_api.log (It shows below error)

Traceback (most recent call last):
  File "/home/uzair/project/SWE-agent/sweagent/api/server.py", line 22, in <module>
    from sweagent import CONFIG_DIR, PACKAGE_DIR
ModuleNotFoundError: No module named 'sweagent'''' the 

### Error message/results

When I check web_api.log (It shows below error)

Traceback (most recent call last):
  File "/home/uzair/project/SWE-agent/sweagent/api/server.py", line 22, in <module>
    from sweagent import CONFIG_DIR, PACKAGE_DIR
ModuleNotFoundError: No module named 'sweagent'the 

### System Information

I am using windows based subsystem linux having 16 gb ram and intel core i7Windows

### Checklist

- [X] I'm running with the latest docker container/on the latest development version
- [X] I've searched the other issues for a duplicate
- [X] I have copied the full command/code that I ran (as text, not as screenshot!)
- [X] If applicable: I have copied the **full** log file/error message that was the result (as text, not as screenshot!)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
Did you install swe-agent? `ModuleNotFoundError: No module named 'sweagent'` shows that swe-agent wasn't installed. Please following the installation instructions in the `Install from source` section of the docs.
