### ISSUE TITLE
Occasional `docker.errors.NotFound` during testing

### ISSUE THREAD

**Issue by klieret** [princeton-nlp/SWE-agent#413]
> [!note]
> If someone else encounters this, I'd appreciate full tracebacks/logs/commands to help debugging.
> As far as workarounds, you should probably simply be able to start your run again; this seems to happen only occasionally.

```
==================================== ERRORS ====================================
___________________ ERROR at teardown of test_env_with_hook ____________________

self = <docker.api.client.APIClient object at 0x7f1ef9b645e0>
response = <Response [404]>

    def _raise_for_status(self, response):
        """Raises stored :class:`APIError`, if one occurred."""
        try:
>           response.raise_for_status()

/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/docker/api/client.py:275: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Response [404]>

    def raise_for_status(self):
        """Raises :class:`HTTPError`, if one occurred."""
    
        http_error_msg = ""
        if isinstance(self.reason, bytes):
            # We attempt to decode utf-8 first because some servers
            # choose to localize their reason strings. If the string
    resp = self.client.api.inspect_container(container_id)
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/docker/utils/decorators.py:19: in wrapped
    return f(self, resource_id, *args, **kwargs)
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/docker/api/container.py:793: in inspect_container
    return self._result(
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/docker/api/client.py:281: in _result
    self._raise_for_status(response)
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/docker/api/client.py:277: in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

e = HTTPError('404 Client Error: Not Found for url: http+docker://localhost/v1.43/containers/test-container-134245890345098/json')

    def create_api_error_from_http_exception(e):
        """
        Create a suitable APIError from requests.exceptions.HTTPError.
        """
        response = e.response
        try:
            explanation = response.json()['message']
        except ValueError:
            explanation = (response.text or '').strip()
        cls = APIError
        if response.status_code == 404:
            explanation_msg = (explanation or '').lower()
            if any(fragment in explanation_msg
                   for fragment in _image_not_found_explanation_fragments):
                cls = ImageNotFound
            else:
                cls = NotFound
>       raise cls(e, response=response, explanation=explanation) from e
E       docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.43/containers/test-container-134245890345098/json: Not Found ("No such container: test-container-134245890345098")

/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/docker/errors.py:39: NotFound
```

**Comment by JiyangZhang** [comment]
I also had similar issues. And sometimes the error is 
`Error response from daemon: Conflict. The container name "/sweagent-swe-agent-latest-4982435ec6" is already in use by container "df022960aebebfd6a2935c0ce2fa030733b5b7e7".`

I guess it is all related to initializing the docker. I would like to know if there is any quick fix for retrying starting a container.

Thanks!

**Comment by klieret** [comment]
@JiyangZhang Thanks, I never encountered this. I created a new issue for your error message.

**Comment by klieret** [comment]
> [!note]
> If someone else encounters this, I'd appreciate full tracebacks/logs/commands to help debugging.
> As far as workarounds, you should probably simply be able to start your run again; this seems to happen only occasionally.

**Comment by JiyangZhang** [comment]
Here is my logs. I had this when i running claude-3-sonnet on swe-bench-lite test set and it just randomly occured.
```
2024-05-29 06:26:30,938 - ERROR: Install command failed to execute successfully: Obtaining file:///astropy__astropy
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/root/miniconda3/envs/astropy__astropy__5.1/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/miniconda3/envs/astropy__astropy__5.1/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/miniconda3/envs/astropy__astropy__5.1/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 448, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 69, in <module>
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/extension_helpers/_setup_helpers.py", line 63, in get_extensions
          for setuppkg in iter_setup_packages(srcdir, packages):
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/extension_helpers/_setup_helpers.py", line 159, in iter_setup_packages
          module = import_file(setup_package, name=packagename + ".setup_package")
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/extension_helpers/_utils.py", line 136, in import_file
          loader.exec_module(mod)
        File "<frozen importlib._bootstrap_external>", line 850, in exec_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "./astropy/wcs/setup_package.py", line 13, in <module>
          from setuptools.dep_util import newer_group
      ModuleNotFoundError: No module named 'setuptools.dep_util'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

2024-05-29 06:26:30,948 - INFO: Beginning environment shutdown...
2024-05-29 06:26:35,105 - INFO: Agent container stopped
2024-05-29 06:26:35,106 - WARNING: ❌ Failed on astropy__astropy-14182: Install command failed to execute successfully: Obtaining file:///astropy__astropy
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/root/miniconda3/envs/astropy__astropy__5.1/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/miniconda3/envs/astropy__astropy__5.1/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/miniconda3/envs/astropy__astropy__5.1/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 448, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 69, in <module>
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/extension_helpers/_setup_helpers.py", line 63, in get_extensions
          for setuppkg in iter_setup_packages(srcdir, packages):
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/extension_helpers/_setup_helpers.py", line 159, in iter_setup_packages
          module = import_file(setup_package, name=packagename + ".setup_package")
        File "/tmp/pip-build-env-97mjn3fg/overlay/lib/python3.9/site-packages/extension_helpers/_utils.py", line 136, in import_file
          loader.exec_module(mod)
        File "<frozen importlib._bootstrap_external>", line 850, in exec_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "./astropy/wcs/setup_package.py", line 13, in <module>
          from setuptools.dep_util import newer_group
      ModuleNotFoundError: No module named 'setuptools.dep_util'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

2024-05-29 06:26:35,117 - INFO: Beginning environment shutdown...
2024-05-29 06:26:35,127 - INFO: Agent container stopped
2024-05-29 06:26:35,148 - INFO: Found image sweagent/swe-agent:latest with tags: ['sweagent/swe-agent:latest'], created: 2024-05-21T20:40:44.507529381Z for linux amd64.
2024-05-29 06:26:35,150 - DEBUG: Starting container with command: docker run -i --rm --name sweagent-swe-agent-latest-101af4cb7f sweagent/swe-agent:latest /bin/bash -l
2024-05-29 06:26:40,196 - DEBUG: Couldn't find container. Let's wait and retry.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/sweagent-swe-agent-latest-101af4cb7f/json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sweagent/environment/swe_env.py", line 507, in _init_container
    self.container_obj = client.containers.get(self.container_name)
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/models/containers.py", line 951, in get
    resp = self.client.api.inspect_container(container_id)
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/api/container.py", line 792, in inspect_container
    return self._result(
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/sweagent-swe-agent-latest-101af4cb7f/json: Not Found ("No such container: sweagent-swe-agent-latest-101af4cb7f")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/sweagent-swe-agent-latest-101af4cb7f/json

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/run.py", line 525, in <module>
    main(get_args())
  File "/run.py", line 521, in main
    Main(args).main()
  File "/run.py", line 408, in main
    self.env.reset_container()
  File "/sweagent/environment/swe_env.py", line 478, in reset_container
    self._reset_container()
  File "/sweagent/environment/swe_env.py", line 471, in _reset_container
    self._init_container()
  File "/sweagent/environment/swe_env.py", line 511, in _init_container
    self.container_obj = client.containers.get(self.container_name)
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/models/containers.py", line 951, in get
    resp = self.client.api.inspect_container(container_id)
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/api/container.py", line 792, in inspect_container
    return self._result(
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/opt/conda/envs/swe-agent/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/sweagent-swe-agent-latest-101af4cb7f/json: Not Found ("No such container: sweagent-swe-agent-latest-101af4cb7f")
```

**Comment by klieret** [comment]
So we're already checking if we get a `docker.errors.NotFound` and waiting 3s more if we do. Perhaps we just have to extend that time a bit. I'll also try to inject a bit more debugging code.
