### ISSUE TITLE
Critical error: not found in configuration: OPENAI_API_KEY

### ISSUE THREAD

**Issue by eabdelmoneim** [princeton-nlp/SWE-agent#421]
### Describe the bug

I'm running python version `3.11.3` on mac and am seeing error `Critical error: not found in configuration: OPENAI_API_KEY` when running ./start_web_ui.sh script.  

I have created a `keys.cfg` in the root directory which contains one entry:

OPENAI_API_KEY: 'sk-proj-XXXXX'

### Steps/commands/code to Reproduce

Run through the installation steps in docs

### Error message/results

```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/config/__init__.py", line 198, in __getitem__
    result = config._evaluated(data[key])
                               ~~~~^^^^^
KeyError: 'OPENAI_API_KEY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/eimanabdelmoneim/Development/ai/SWE-agent/sweagent/api/server.py", line 75, in run
    main = Main(self._settings)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/eimanabdelmoneim/Development/ai/SWE-agent/run.py", line 304, in __init__
    self.agent = Agent("primary", args.agent)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eimanabdelmoneim/Development/ai/SWE-agent/sweagent/agent/agents.py", line 253, in __init__
    self.model = get_model(
                 ^^^^^^^^^^
  File "/Users/eimanabdelmoneim/Development/ai/SWE-agent/sweagent/agent/models.py", line 875, in get_model
    return OpenAIModel(args, commands)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eimanabdelmoneim/Development/ai/SWE-agent/sweagent/agent/models.py", line 248, in __init__
    self.client = OpenAI(api_key=cfg["OPENAI_API_KEY"], base_url=api_base_url)
                                 ~~~^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/config/__init__.py", line 771, in __getitem__
    result = self._data[key]
             ~~~~~~~~~~^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/config/__init__.py", line 200, in __getitem__
    raise KeyNotFoundError('not found in configuration: %s' % key)
config.KeyNotFoundError: not found in configuration: OPENAI_API_KEY
```

### System Information

MacOS M2 v14.5

```/Users/eimanabdelmoneim/Development/ai> python -V```
```Python 3.11.3```

### Checklist

- [X] I'm running with the latest docker container/on the latest development version
- [X] I've searched the other issues for a duplicate
- [X] I have copied the full command/code that I ran (as text, not as screenshot!)
- [X] If applicable: I have copied the **full** log file/error message that was the result (as text, not as screenshot!)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by eabdelmoneim** [comment]
root directory
<img width="1286" alt="Screenshot 2024-05-27 at 1 29 35 PM" src="https://github.com/princeton-nlp/SWE-agent/assets/10700302/ad291886-0f18-48f1-81ea-aa911ca4ff55">

**Comment by klieret** [comment]
Please include the full log and command that you ran! 

Also, what's the output of

```
import config
c = config.Config("keys.cfg")
"OPENAI_API_KEY" in c
```

as executed in the root of the repo?

**Comment by eabdelmoneim** [comment]
Issue is resolved now.  I had a weird thing happening on my machine in which files were not saving in vs code with command-S which means my keys.cfg wasn't actually being saved. once I saved it this worked as expected. 

closing issue
