### ISSUE TITLE
404 Not Found when retrieving repository information

### ISSUE THREAD

**Issue by SashvDave** [princeton-nlp/SWE-agent#662]
### Describe the bug

Returning a 404 not found at runtime seeking a documentation URL

### Steps/commands/code to Reproduce

Set up the software via github codespaces. simply ran ```./start_web_ui.sh``` and the frontend via ```npm start```.

### Error message/results

```2024-07-12 23:34:12,053 - werkzeug - WARNING - Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
 * Serving Flask app 'server'
 * Debug mode: on
2024-07-12 23:34:12,056 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8000
2024-07-12 23:34:12,056 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-07-12 23:34:12,056 - werkzeug - INFO -  * Restarting with stat
2024-07-12 23:34:14,520 - werkzeug - WARNING - Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
2024-07-12 23:34:14,521 - werkzeug - WARNING -  * Debugger is active!
2024-07-12 23:34:14,522 - werkzeug - INFO -  * Debugger PIN: 132-206-430
2024-07-12 23:34:16,617 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:34:16] "GET /socket.io/?EIO=4&transport=polling&t=P2fJ1uG HTTP/1.1" 200 -
2024-07-12 23:34:16,820 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:34:16] "POST /socket.io/?EIO=4&transport=polling&t=P2fJ1-s&sid=Fn4pKRplQOKtpkJsAAAA HTTP/1.1" 200 -
2024-07-12 23:34:17,031 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:34:17] "GET /socket.io/?EIO=4&transport=polling&t=P2fJ1-u&sid=Fn4pKRplQOKtpkJsAAAA HTTP/1.1" 200 -
2024-07-12 23:34:39,977 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:34:39] "GET /socket.io/?EIO=4&transport=polling&t=P2fJ23b&sid=Fn4pKRplQOKtpkJsAAAA HTTP/1.1" 200 -
2024-07-12 23:34:40,001 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:34:40] "[35m[1mGET /run?runConfig={"agent":{"model":{"model_name":"gpt4"}},"environment":{"data_path":"text://Finish+implementing+the+feature+of+being+able+to+add+recommendations+through+the+add+recommendations+modal,+pushing+those+up+to+supabase,+and+allowing+other+users+to+see+those+recommendations","repo_path":"https://github.com/SashvDave/recco.git","base_commit":"","environment_setup":{"input_type":"manual","manual":{"python":"3.10","config_type":"manual","install":"pip+install+--editable+.","install_command_active":true,"pip_packages":""},"script_path":{"script_path":""}}},"extra":{"test_run":false}} HTTP/1.1[0m" 202 -
2024-07-12 23:34:40,062 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:34:40] "GET /socket.io/?EIO=4&transport=polling&t=P2fJ7gA&sid=Fn4pKRplQOKtpkJsAAAA HTTP/1.1" 200 -
2024-07-12 23:34:40,156 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:34:40] "GET /socket.io/?EIO=4&transport=polling&t=P2fJ7hu&sid=Fn4pKRplQOKtpkJsAAAA HTTP/1.1" 200 -
Exception in thread Thread-9:
2024-07-12 23:34:40,451 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:34:40] "GET /socket.io/?EIO=4&transport=polling&t=P2fJ7j5&sid=Fn4pKRplQOKtpkJsAAAA HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/workspaces/SWE-agent/sweagent/api/server.py", line 71, in run
    main = Main(self._settings)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/SWE-agent/run.py", line 319, in __init__
    self.env = SWEEnv(args.environment)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/SWE-agent/sweagent/environment/swe_env.py", line 168, in __init__
    self.data = get_instances(
                ^^^^^^^^^^^^^^
  File "/workspaces/SWE-agent/sweagent/environment/utils.py", line 667, in get_instances
    ib.set_repo_info(repo_path, base_commit=base_commit)
  File "/workspaces/SWE-agent/sweagent/environment/utils.py", line 582, in set_repo_info
    self.set_repo_info_from_gh_url(repo, base_commit=base_commit)
  File "/workspaces/SWE-agent/sweagent/environment/utils.py", line 558, in set_repo_info_from_gh_url
    self.args["base_commit"] = get_commit(api, owner, repo, ref=base_commit).sha
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/SWE-agent/sweagent/environment/utils.py", line 447, in get_commit
    return api.repos.list_commits(owner, repo)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/ghapi/core.py", line 62, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/ghapi/core.py", line 121, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=debug, return_headers=True,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/fastcore/net.py", line 219, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/fastcore/net.py", line 120, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp, msg=e.msg) from None
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastcore.net.HTTP404NotFoundError: HTTP Error 404: Not Found
====Error Body====
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/commits/commits#list-commits",
  "status": "404"
}

2024-07-12 23:34:41,617 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:34:41] "GET /socket.io/?EIO=4&transport=polling&t=P2fJ7nx&sid=Fn4pKRplQOKtpkJsAAAA HTTP/1.1" 200 -
2024-07-12 23:34:41,697 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:34:41] "POST /socket.io/?EIO=4&transport=polling&t=P2fJ83k&sid=Fn4pKRplQOKtpkJsAAAA HTTP/1.1" 200 -
2024-07-12 23:34:58,449 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:34:58] "GET /socket.io/?EIO=4&transport=polling&t=P2fJC5k HTTP/1.1" 200 -
2024-07-12 23:34:58,557 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:34:58] "POST /socket.io/?EIO=4&transport=polling&t=P2fJCBU&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
2024-07-12 23:34:58,558 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:34:58] "GET /socket.io/?EIO=4&transport=polling&t=P2fJCBV&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
2024-07-12 23:35:06,697 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:06] "GET /socket.io/?EIO=4&transport=polling&t=P2fJ83k.0&sid=Fn4pKRplQOKtpkJsAAAA HTTP/1.1" 200 -
2024-07-12 23:35:08,500 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:08] "GET /socket.io/?EIO=4&transport=polling&t=P2fJCCd&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
2024-07-12 23:35:08,519 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:08] "[35m[1mGET /run?runConfig={"agent":{"model":{"model_name":"gpt4"}},"environment":{"data_path":"text://Finish+implementing+the+feature+of+being+able+to+add+recommendations+through+the+add+recommendations+modal,+pushing+those+up+to+supabase,+and+allowing+other+users+to+see+those+recommendations","repo_path":"https://github.com/SashvDave/recco.git","base_commit":"","environment_setup":{"input_type":"manual","manual":{"python":"3.10","config_type":"manual","install":"pip+install+--editable+.","install_command_active":true,"pip_packages":""},"script_path":{"script_path":""}}},"extra":{"test_run":false}} HTTP/1.1[0m" 202 -
2024-07-12 23:35:08,568 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:08] "GET /socket.io/?EIO=4&transport=polling&t=P2fJEdq&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
2024-07-12 23:35:08,722 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:08] "GET /socket.io/?EIO=4&transport=polling&t=P2fJEfJ&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
Exception in thread Thread-23:
2024-07-12 23:35:09,016 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:09] "GET /socket.io/?EIO=4&transport=polling&t=P2fJEhS&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/workspaces/SWE-agent/sweagent/api/server.py", line 71, in run
    main = Main(self._settings)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/SWE-agent/run.py", line 319, in __init__
    self.env = SWEEnv(args.environment)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/SWE-agent/sweagent/environment/swe_env.py", line 168, in __init__
    self.data = get_instances(
                ^^^^^^^^^^^^^^
  File "/workspaces/SWE-agent/sweagent/environment/utils.py", line 667, in get_instances
    ib.set_repo_info(repo_path, base_commit=base_commit)
  File "/workspaces/SWE-agent/sweagent/environment/utils.py", line 582, in set_repo_info
    self.set_repo_info_from_gh_url(repo, base_commit=base_commit)
  File "/workspaces/SWE-agent/sweagent/environment/utils.py", line 558, in set_repo_info_from_gh_url
    self.args["base_commit"] = get_commit(api, owner, repo, ref=base_commit).sha
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/SWE-agent/sweagent/environment/utils.py", line 447, in get_commit
    return api.repos.list_commits(owner, repo)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/ghapi/core.py", line 62, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/ghapi/core.py", line 121, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=debug, return_headers=True,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/fastcore/net.py", line 219, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/fastcore/net.py", line 120, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp, msg=e.msg) from None
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastcore.net.HTTP404NotFoundError: HTTP Error 404: Not Found
====Error Body====
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/commits/commits#list-commits",
  "status": "404"
}

2024-07-12 23:35:23,450 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:23] "GET /socket.io/?EIO=4&transport=polling&t=P2fJElv&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
2024-07-12 23:35:23,530 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:23] "POST /socket.io/?EIO=4&transport=polling&t=P2fJIHO&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
2024-07-12 23:35:36,277 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:36] "GET /socket.io/?EIO=4&transport=polling&t=P2fJIHQ&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
2024-07-12 23:35:36,295 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:36] "[35m[1mGET /run?runConfig={"agent":{"model":{"model_name":"gpt4"}},"environment":{"data_path":"text://Finish+implementing+the+feature+of+being+able+to+add+recommendations+through+the+add+recommendations+modal,+pushing+those+up+to+supabase,+and+allowing+other+users+to+see+those+recommendations","repo_path":"https://github.com/SashvDave/recco.git","base_commit":"","environment_setup":{"input_type":"manual","manual":{"python":"3.10","config_type":"manual","install":"pip+install+--editable+.","install_command_active":true,"pip_packages":""},"script_path":{"script_path":""}}},"extra":{"test_run":true}} HTTP/1.1[0m" 202 -
2024-07-12 23:35:36,463 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:36] "GET /socket.io/?EIO=4&transport=polling&t=P2fJLPv&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/workspaces/SWE-agent/sweagent/api/server.py", line 71, in run
    main = Main(self._settings)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/SWE-agent/run.py", line 319, in __init__
    self.env = SWEEnv(args.environment)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/SWE-agent/sweagent/environment/swe_env.py", line 168, in __init__
    self.data = get_instances(
                ^^^^^^^^^^^^^^
  File "/workspaces/SWE-agent/sweagent/environment/utils.py", line 667, in get_instances
    ib.set_repo_info(repo_path, base_commit=base_commit)
  File "/workspaces/SWE-agent/sweagent/environment/utils.py", line 582, in set_repo_info
    self.set_repo_info_from_gh_url(repo, base_commit=base_commit)
  File "/workspaces/SWE-agent/sweagent/environment/utils.py", line 558, in set_repo_info_from_gh_url
    self.args["base_commit"] = get_commit(api, owner, repo, ref=base_commit).sha
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/SWE-agent/sweagent/environment/utils.py", line 447, in get_commit
    return api.repos.list_commits(owner, repo)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/ghapi/core.py", line 62, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/ghapi/core.py", line 121, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=debug, return_headers=True,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/fastcore/net.py", line 219, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/fastcore/net.py", line 120, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp, msg=e.msg) from None
2024-07-12 23:35:36,671 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:36] "GET /socket.io/?EIO=4&transport=polling&t=P2fJLT6&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastcore.net.HTTP404NotFoundError: HTTP Error 404: Not Found
====Error Body====
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/commits/commits#list-commits",
  "status": "404"
}

2024-07-12 23:35:48,530 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:48] "GET /socket.io/?EIO=4&transport=polling&t=P2fJLW3&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
2024-07-12 23:35:48,686 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:35:48] "POST /socket.io/?EIO=4&transport=polling&t=P2fJOQj&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
2024-07-12 23:36:13,686 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:36:13] "GET /socket.io/?EIO=4&transport=polling&t=P2fJOQk&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
2024-07-12 23:36:13,771 - werkzeug - INFO - 127.0.0.1 - - [12/Jul/2024 23:36:13] "POST /socket.io/?EIO=4&transport=polling&t=P2fJUYU&sid=qVp6Mi9rU4PVPN0TAAAC HTTP/1.1" 200 -
```

### System Information

MacOS M1, python version 3.12.3

### Checklist

- [X] I'm running with the latest docker container/on the latest development version (this means running both `git pull` and `docker pull sweagent/swe-agent:latest`)
- [X] I have copied the full command/code that I ran (as text, not as screenshot!)
- [X] If applicable: I have copied the **full** log file/error message that was the result (as text, not as screenshot!)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
What was the path that you used for the issue and the repo? The error is because it couldn't retrieve commit information from the repository. Did you specify a private repository without setting a github API key?

**Comment by klieret** [comment]
Hmm, I just tested it myself and I do not have any issues. Can you double check your key?

**Comment by klieret** [comment]
No specific python project should be set up unless you specify it (see the [docs](https://princeton-nlp.github.io/SWE-agent/usage/cl_tutorial/#installing-dependencies-and-setting-up-the-environment)). If you believe you have found a bug, please open a bug report with all the required information (I have tried but could not reproduce any issue so far).
