### ISSUE TITLE
How to run evaluation after patch has been created?

### ISSUE THREAD

**Issue by MAhmadUzair** [princeton-nlp/SWE-agent#710]
### Describe the issue

![Screenshot_1](https://github.com/user-attachments/assets/1a6a314e-4770-47da-bc59-67786af0c017)
```
 # The patch has been saved to your local filesystem at:
 PATCH_FILE_PATH='/home/uzair/SWE-agent/trajectories/uzair/llama-3.1-70b__TandoorRecipes__recipes__default_from_url__t-0.00__p-0.95__c-3.00__in
 all-1/patches/TandoorRecipes__recipes-i2857.patch'
 # Inspect it:
 cat "${PATCH_FILE_PATH}"
 # Apply it to a local repository:
 cd <your local repo root>
 git apply "${PATCH_FILE_PATH}"

uzair@UZAIR:~/SWE-agent$ python3.11 -m swebench.harness.run_evaluation --predictions_path /path/to/all_preds.jsonl --max_workers 1 --run_id test
<frozen runpy>:128: RuntimeWarning: 'swebench.harness.run_evaluation' found in sys.modules after import of package 'swebench.harness', but prior to execution of 'swebench.harness.run_evaluation'; this may result in unpredictable behaviour
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/uzair/.local/lib/python3.11/site-packages/swebench/harness/run_evaluation.py", line 579, in <module>
    main(**vars(args))
  File "/home/uzair/.local/lib/python3.11/site-packages/swebench/harness/run_evaluation.py", line 527, in main
    with open(predictions_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/all_preds.jsonl'
uzair@UZAIR:~/SWE-agent$ python3.11 -m swebench.harness.run_evaluation --predictions_path /TandoorRecipes__recipes-i2857.patch/all_preds.jsonl --max_workers 1 --run_id test
<frozen runpy>:128: RuntimeWarning: 'swebench.harness.run_evaluation' found in sys.modules after import of package 'swebench.harness', but prior to execution of 'swebench.harness.run_evaluation'; this may result in unpredictable behaviour
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/uzair/.local/lib/python3.11/site-packages/swebench/harness/run_evaluation.py", line 579, in <module>
    main(**vars(args))
  File "/home/uzair/.local/lib/python3.11/site-packages/swebench/harness/run_evaluation.py", line 527, in main
    with open(predictions_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/TandoorRecipes__recipes-i2857.patch/all_preds.jsonl'
```
![Screenshot_1](https://github.com/user-attachments/assets/de29cb6b-cc41-417e-9eec-62b69eadbe9c)

**Comment by klieret** [comment]
You have to replace `/path/to/all_preds.jsonl` with the path to your `all_preds.jsonl`. Please don't use screenshots in issues

**Comment by dashesy** [comment]
@klieret after `sweaget run-batch` I do not see any `all_preds.jsonl` file created just some individual .patch files
