### ISSUE TITLE
Can You explain in proper way how to run the swe bench evaluation on swe agent?

### ISSUE THREAD

**Issue by MAhmadUzair** [princeton-nlp/SWE-agent#711]
### Describe the issue

What I did?

I started from cloning your repo and setting up all things. then I went to your benchmarking page of your documentation. There I found the guide to run swe bench for singly instance using this command.

```
python3.11 run.py --model_name llama-3.1-70b --instance_filter marshmallow-code__marshmallow-1359

```

After successfull run, It created patch 

patch
```

 # The patch has been saved to your local filesystem at:
 PATCH_FILE_PATH='/home/uzair/SWE-agent/trajectories/uzair/llama-3.1-70b__SWE-bench_Lite__default__t-0.00__p-0.95__c-3.00__install-1/patches/ma
 hmallow-code__marshmallow-1359.patch'
 # Inspect it:
 cat "${PATCH_FILE_PATH}"
 # Apply it to a local repository:
 cd <your local repo root>
 git apply "${PATCH_FILE_PATH}"
```

and the I tried to put the path of all_pred/_jsonl into given command like below:

```
python3.11 -m swebench.harness.run_evaluation --predictions_path /home/uzair/SWE-agent/trajectories/uzair/llama-3.1-70b__SWE-bench_Lite__default__t-0.00__p-0.95__c-3.00__install-1/all_preds.jsonl --max_workers 1 --run_id test

```

but it gave me some error of instance id not found.

I also followed your below repo

```
https://github.com/princeton-nlp/SWE-bench/
```

But it is getting all mixed. In dataset it shows instance id is missing?

```
uzair@UZAIR:~/SWE-agent$ python3.11 -m swebench.harness.run_evaluation --predictions_path /home/uzair/SWE-agent/trajectories/uzair/llama-3.1-70b__SWE-bench_Lite__default__t-0.00__p-0.95__c-3.00__install-1/all_preds.jsonl --max_workers 1 --run_id test
<frozen runpy>:128: RuntimeWarning: 'swebench.harness.run_evaluation' found in sys.modules after import of package 'swebench.harness', but prior to execution of 'swebench.harness.run_evaluation'; this may result in unpredictable behaviour
{'django__django-12700', 'sympy__sympy-13773', 'django__django-13658', 'psf__requests-3362', 'django__django-14608', 'django__django-15790', 'pytest-dev__pytest-8365', 'sympy__sympy-13177', 'django__django-15819', 'mwaskom__seaborn-3190', 'sympy__sympy-14024', 'sympy__sympy-18057', 'django__django-16816', 'django__django-15202', 'matplotlib__matplotlib-23987', 'django__django-14534', 'sympy__sympy-13437', 'django__django-13551', 'django__django-11999', 'django__django-10914', 'scikit-learn__scikit-learn-10297', 'sympy__sympy-20154', 'django__django-13660', 'astropy__astropy-14182', 'django__django-12497', 'pallets__flask-4045', 'pydata__xarray-4493', 'django__django-11815', 'scikit-learn__scikit-learn-25570', 'matplotlib__matplotlib-25311', 'pytest-dev__pytest-5221', 'sympy__sympy-16281', 'scikit-learn__scikit-learn-13779', 'pydata__xarray-3364', 'sympy__sympy-20639', 'astropy__astropy-6938', 'django__django-11905', 'django__django-12983', 'matplotlib__matplotlib-23299', 'django__django-17051', 'matplotlib__matplotlib-24265', 'django__django-15388', 'sympy__sympy-11400', 'sympy__sympy-17655', 'sympy__sympy-20442', 'matplotlib__matplotlib-23314', 'sympy__sympy-12419', 'pytest-dev__pytest-9359', 'matplotlib__matplotlib-23476', 'sphinx-doc__sphinx-10451', 'matplotlib__matplotlib-23563', 'sympy__sympy-17630', 'django__django-16527', 'psf__requests-1963', 'sympy__sympy-13043', 'sympy__sympy-20590', 'pylint-dev__pylint-5859', 'django__django-14855', 'mwaskom__seaborn-2848', 'django__django-14017', 'django__django-13933', 'sphinx-doc__sphinx-11445', 'astropy__astropy-12907', 'sympy__sympy-21379', 'scikit-learn__scikit-learn-25747', 'sympy__sympy-12236', 'django__django-15252', 'django__django-13447', 'astropy__astropy-14995', 'sphinx-doc__sphinx-8721', 'django__django-15851', 'sympy__sympy-22005', 'sympy__sympy-14308', 'django__django-11742', 'scikit-learn__scikit-learn-15512', 'django__django-13265', 'sympy__sympy-18087', 'sphinx-doc__sphinx-7686', 'scikit-learn__scikit-learn-11040', 'sphinx-doc__sphinx-8627', 'matplotlib__matplotlib-25079', 'sphinx-doc__sphinx-8506', 'pytest-dev__pytest-7432', 'astropy__astropy-7746', 'sympy__sympy-23262', 'django__django-11583', 'django__django-14238', 'scikit-learn__scikit-learn-13496', 'sympy__sympy-15609', 'sympy__sympy-13031', 'sympy__sympy-14396', 'sympy__sympy-18532', 'psf__requests-2148', 'matplotlib__matplotlib-23964', 'django__django-11630', 'psf__requests-2317', 'sympy__sympy-15011', 'sympy__sympy-20049', 'django__django-12908', 'django__django-15213', 'sympy__sympy-12454', 'sympy__sympy-14817', 'pylint-dev__pylint-7114', 'django__django-13028', 'matplotlib__matplotlib-22711', 'pytest-dev__pytest-7168', 'sympy__sympy-21614', 'django__django-17087', 'matplotlib__matplotlib-22835', 'django__django-16255', 'django__django-13757', 'sympy__sympy-13471', 'pytest-dev__pytest-5692', 'django__django-14580', 'pytest-dev__pytest-5413', 'matplotlib__matplotlib-18869', 'sphinx-doc__sphinx-8801', 'sympy__sympy-15346', 'pylint-dev__pylint-7993', 'pydata__xarray-4248', 'django__django-12453', 'pallets__flask-5063', 'scikit-learn__scikit-learn-13241', 'sphinx-doc__sphinx-10325', 'django__django-11564', 'sympy__sympy-13895', 'matplotlib__matplotlib-24970', 'django__django-16046', 'django__django-12589', 'sympy__sympy-19487', 'sympy__sympy-20322', 'sympy__sympy-18621', 'django__django-15061', 'django__django-13710', 'sympy__sympy-24066', 'django__django-16873', 'sympy__sympy-18199', 'scikit-learn__scikit-learn-15535', 'django__django-12113', 'scikit-learn__scikit-learn-13142', 'pytest-dev__pytest-6116', 'matplotlib__matplotlib-26011', 'django__django-13964', 'matplotlib__matplotlib-23562', 'sympy__sympy-18698', 'sympy__sympy-21055', 'sympy__sympy-22714', 'pytest-dev__pytest-5103', 'pytest-dev__pytest-7373', 'django__django-14016', 'django__django-14411', 'django__django-13315', 'django__django-15814', 'sphinx-doc__sphinx-8474', 'sphinx-doc__sphinx-7738', 'pytest-dev__pytest-8906', 'sympy__sympy-17022', 'django__django-11848', 'django__django-11283', 'matplotlib__matplotlib-26020', 'sympy__sympy-15345', 'sympy__sympy-24909', 'django__django-15320', 'pydata__xarray-4094', 'sympy__sympy-15678', 'sympy__sympy-21612', 'django__django-11019', 'django__django-16595', 'django__django-15498', 'matplotlib__matplotlib-25498', 'django__django-13925', 'django__django-10924', 'sympy__sympy-12171', 'django__django-12856', 'scikit-learn__scikit-learn-13439', 'sympy__sympy-24102', 'psf__requests-2674', 'django__django-12915', 'matplotlib__matplotlib-24149', 'scikit-learn__scikit-learn-25500', 'pallets__flask-4992', 'django__django-11001', 'django__django-15695', 'scikit-learn__scikit-learn-12471', 'sympy__sympy-13647', 'django__django-11039', 'pydata__xarray-5131', 'sympy__sympy-16503', 'matplotlib__matplotlib-23913', 'django__django-12470', 'django__django-14752', 'django__django-11620', 'django__django-15996', 'scikit-learn__scikit-learn-14087', 'sphinx-doc__sphinx-8435', 'sympy__sympy-13146', 'sympy__sympy-24152', 'django__django-11422', 'django__django-13220', 'sympy__sympy-17139', 'django__django-11910', 'pylint-dev__pylint-7080', 'django__django-16229', 'django__django-11133', 'sympy__sympy-24213', 'django__django-16910', 'django__django-13158', 'sympy__sympy-16106', 'django__django-15902', 'sympy__sympy-21171', 'django__django-16379', 'django__django-16820', 'sympy__sympy-18835', 'django__django-11179', 'django__django-15738', 'pytest-dev__pytest-11148', 'pytest-dev__pytest-5227', 'mwaskom__seaborn-3407', 'matplotlib__matplotlib-24334', 'sympy__sympy-12481', 'matplotlib__matplotlib-25332', 'matplotlib__matplotlib-25442', 'django__django-14382', 'scikit-learn__scikit-learn-10508', 'sympy__sympy-13971', 'django__django-11099', 'sympy__sympy-19254', 'django__django-14155', 'django__django-16400', 'sympy__sympy-14774', 'sympy__sympy-22840', 'scikit-learn__scikit-learn-14092', 'django__django-15781', 'mwaskom__seaborn-3010', 'pytest-dev__pytest-5495', 'sphinx-doc__sphinx-8273', 'scikit-learn__scikit-learn-14983', 'django__django-13033', 'sympy__sympy-23191', 'scikit-learn__scikit-learn-25638', 'psf__requests-863', 'scikit-learn__scikit-learn-13497', 'sphinx-doc__sphinx-8282', 'django__django-11964', 'django__django-12308', 'django__django-13230', 'django__django-13401', 'django__django-12284', 'sympy__sympy-16988', 'astropy__astropy-14365', 'sympy__sympy-11897', 'django__django-14667', 'sympy__sympy-13480', 'pylint-dev__pylint-7228', 'pytest-dev__pytest-11143', 'sympy__sympy-21847', 'django__django-12747', 'django__django-14730', 'pytest-dev__pytest-7220', 'scikit-learn__scikit-learn-14894', 'sympy__sympy-21627', 'django__django-15789', 'sympy__sympy-19007', 'django__django-12125', 'sympy__sympy-11870', 'django__django-16139', 'django__django-16041', 'django__django-13768', 'scikit-learn__scikit-learn-11281', 'sympy__sympy-18189', 'django__django-12708', 'django__django-16408', 'sphinx-doc__sphinx-7975', 'sphinx-doc__sphinx-8713', 'pylint-dev__pylint-6506', 'django__django-14672', 'django__django-14915', 'pytest-dev__pytest-7490', 'sympy__sympy-13915', 'scikit-learn__scikit-learn-13584', 'sympy__sympy-20212', 'django__django-14787', 'django__django-14997', 'django__django-15400', 'matplotlib__matplotlib-25433', 'sympy__sympy-14317', 'django__django-13590', 'django__django-12184', 'sympy__sympy-16792', 'django__django-14999', 'sphinx-doc__sphinx-8595', 'django__django-13448', 'django__django-11049', 'scikit-learn__scikit-learn-10949', 'django__django-12286', 'django__django-13321', 'sympy__sympy-23117', 'django__django-15347', 'sympy__sympy-15308', 'django__django-11797'}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/uzair/SWE-bench/swebench/harness/run_evaluation.py", line 579, in <module>
    main(**vars(args))
  File "/home/uzair/SWE-bench/swebench/harness/run_evaluation.py", line 534, in main
    dataset = get_dataset_from_preds(dataset_name, split, instance_ids, predictions, run_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uzair/SWE-bench/swebench/harness/run_evaluation.py", line 326, in get_dataset_from_preds
    raise ValueError(
ValueError: Some prediction IDs not found in dataset!
Missing IDs:
marshmallow-code__marshmallow-1359
```
Can you spot the mistake?? Do you have any tutorial video or proper guide specific to this purpose? Thanks.

**Comment by klieret** [comment]
Ahh, I see what's going on. `marshmallow-code__marshmallow-1359` is in the dev split of SWE-B lite, which is the default for running SWE-a. However, the default split of SWE-B is test.

So you have to add `--split test` to the SWE-B command. 

Good question, I'll add it to the documentation.

**Comment by MAhmadUzair** [comment]
Thanks for noticing. Make sure you correctly explain how to & which command to place for the evaluation run.
