### ISSUE TITLE
Container crash after agent calls `su`

### ISSUE THREAD

**Issue by klieret** [princeton-nlp/SWE-agent#738]
```
INFO     🎬 ACTION (primary)
         su -

WARNING  Traceback (most recent call last):
           File "/home/klieret/SWE-agent-ctf/run.py", line 393, in main
             self.run(index)
           File "/home/klieret/SWE-agent-ctf/run.py", line 377, in run
             info, trajectory = self.agent.run(
           File "/home/klieret/SWE-agent-ctf/sweagent/agent/agents.py", line 1049, in run
             observation, done = self._run_step(observation)
           File "/home/klieret/SWE-agent-ctf/sweagent/agent/agents.py", line 966, in _run_step
             thought, action, output = self.forward(observation, self._env.get_available_actions(), state)
           File "/home/klieret/SWE-agent-ctf/sweagent/agent/agents.py", line 644, in forward
             thought, action, output = self.forward_with_error_check(observation, state)
           File "/home/klieret/SWE-agent-ctf/sweagent/agent/agents.py", line 803, in
         forward_with_error_check
             return self.check_format_and_requery(self.forward_model(observation, state))
           File "/home/klieret/SWE-agent-ctf/sweagent/agent/agents.py", line 669, in forward_model
             state_vars = json.loads(state)
           File "/opt/miniconda3/envs/swe-ctf/lib/python3.10/json/__init__.py", line 346, in loads
             return _default_decoder.decode(s)
           File "/opt/miniconda3/envs/swe-ctf/lib/python3.10/json/decoder.py", line 337, in decode
             obj, end = self.raw_decode(s, idx=_w(s, 0).end())
           File "/opt/miniconda3/envs/swe-ctf/lib/python3.10/json/decoder.py", line 355, in raw_decode
             raise JSONDecodeError("Expecting value", s, err.value) from None
         json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by 271-126** [comment]
> ```
> INFO     🎬 ACTION (primary)
>          su -
> 
> WARNING  Traceback (most recent call last):
>            File "/home/klieret/SWE-agent-ctf/run.py", line 393, in main
>              self.run(index)
>            File "/home/klieret/SWE-agent-ctf/run.py", line 377, in run
>              info, trajectory = self.agent.run(
>            File "/home/klieret/SWE-agent-ctf/sweagent/agent/agents.py", line 1049, in run
>              observation, done = self._run_step(observation)
>            File "/home/klieret/SWE-agent-ctf/sweagent/agent/agents.py", line 966, in _run_step
>              thought, action, output = self.forward(observation, self._env.get_available_actions(), state)
>            File "/home/klieret/SWE-agent-ctf/sweagent/agent/agents.py", line 644, in forward
>              thought, action, output = self.forward_with_error_check(observation, state)
>            File "/home/klieret/SWE-agent-ctf/sweagent/agent/agents.py", line 803, in
>          forward_with_error_check
>              return self.check_format_and_requery(self.forward_model(observation, state))
>            File "/home/klieret/SWE-agent-ctf/sweagent/agent/agents.py", line 669, in forward_model
>              state_vars = json.loads(state)
>            File "/opt/miniconda3/envs/swe-ctf/lib/python3.10/json/__init__.py", line 346, in loads
>              return _default_decoder.decode(s)
>            File "/opt/miniconda3/envs/swe-ctf/lib/python3.10/json/decoder.py", line 337, in decode
>              obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>            File "/opt/miniconda3/envs/swe-ctf/lib/python3.10/json/decoder.py", line 355, in raw_decode
>              raise JSONDecodeError("Expecting value", s, err.value) from None
>          json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```

****

**Comment by 7259324177** [comment]
Enfrió tus bases in MTIM by Khaba if you want write me in my DM prívate okay?

**Comment by 7259324177** [comment]
Write me i hace News of SWEagents

**Comment by 7259324177** [comment]
Move to char(2)

**Comment by klieret** [comment]
```
         su
TRACE    Input:
         su
TRACE    Output:

TRACE    Input:
         state
TRACE    Output:
         bash: line 8: state: command not found
Traceback (most recent call last):
  File "/Users/fuchur/Documents/24/git_sync/SWE-agent/run.py", line 381, in main
    self.run(index)
  File "/Users/fuchur/Documents/24/git_sync/SWE-agent/run.py", line 365, in run
    info, trajectory = self.agent.run(
  File "/Users/fuchur/Documents/24/git_sync/SWE-agent/sweagent/agent/agents.py", line 811, in run
    thought, action, output = self.forward(observation, env.get_available_actions(), state)
  File "/Users/fuchur/Documents/24/git_sync/SWE-agent/sweagent/agent/agents.py", line 487, in forward
    thought, action, output = self.forward_with_error_check(observation, state)
  File "/Users/fuchur/Documents/24/git_sync/SWE-agent/sweagent/agent/agents.py", line 645, in forward_with_error_check
    return self.check_format_and_requery(self.forward_model(observation, state))
  File "/Users/fuchur/Documents/24/git_sync/SWE-agent/sweagent/agent/agents.py", line 512, in forward_model
    state_vars = json.loads(state)
  File "/opt/miniconda3/envs/swe-agent/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/miniconda3/envs/swe-agent/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/miniconda3/envs/swe-agent/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by klieret** [comment]
Looks like `su` actually succeeds and then we miss the `state` command because we've changed shells.

Similar: `bash` etc.

**Comment by klieret** [comment]
There's no way around this other than to manually block these commands.
