### ISSUE TITLE
ModuleNotFoundError: No module named 'simple_parsing'

### ISSUE THREAD

**Issue by DrivenIdeaLab** [princeton-nlp/SWE-agent#89]
```
npall@Nathan MINGW64 ~
$ cd documents

npall@Nathan MINGW64 ~/documents
$ cd swe-agent

npall@Nathan MINGW64 ~/documents/swe-agent (main)
$ ./setup.sh
Setting up docker image for swe-agent...
Building the x86 Docker image
2024/04/06 10:26:11 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 1.9s (18/18) FINISHED                                                                       docker:default
 => [internal] load build definition from swe.Dockerfile                                                           0.0s
 => => transferring dockerfile: 1.15kB                                                                             0.0s
 => [internal] load metadata for docker.io/library/ubuntu:jammy                                                    1.8s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                      0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [ 1/13] FROM docker.io/library/ubuntu:jammy@sha256:77906da86b60585ce12215807090eb327e7386c8fafb5402369e421f44  0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 105B                                                                                  0.0s
 => CACHED [ 2/13] RUN apt-get update &&     apt-get install -y bash gcc git jq wget g++ make &&     apt-get clea  0.0s
 => CACHED [ 3/13] RUN git config --global user.email "sweagent@pnlp.org"                                          0.0s
 => CACHED [ 4/13] RUN git config --global user.name "sweagent"                                                    0.0s
 => CACHED [ 5/13] RUN prompt() { echo " > "; };                                                                   0.0s
 => CACHED [ 6/13] RUN touch /root/files_to_edit.txt                                                               0.0s
 => CACHED [ 7/13] RUN touch /root/test.patch                                                                      0.0s
 => CACHED [ 8/13] RUN echo "alias ls='ls -F'" >> /root/.bashrc                                                    0.0s
 => CACHED [ 9/13] RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py39_23.11.0-1-Linux-x86_64.sh -O mini  0.0s
 => CACHED [10/13] RUN conda --version     && conda init bash     && conda config --append channels conda-forge    0.0s
 => CACHED [11/13] COPY docker/requirements.txt /root/requirements.txt                                             0.0s
 => CACHED [12/13] RUN pip install -r /root/requirements.txt                                                       0.0s
 => exporting to image                                                                                             0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:f3e95f3f313c45afd4a59889c3e51ab32ba71db8dd1adf70acb9b4b13d1501c7                       0.0s
 => => naming to docker.io/library/swe-agent                                                                       0.0s

View build details: docker-desktop://dashboard/build/default/default/dhv0k3g83hgdgde12kpz2gjwn

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview
Setting up docker image for evaluation...
2024/04/06 10:26:14 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 0.1s (9/9) FINISHED                                                                         docker:default
 => [internal] load build definition from eval.Dockerfile                                                          0.0s
 => => transferring dockerfile: 238B                                                                               0.0s
 => [internal] load metadata for docker.io/library/swe-agent:latest                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 10.28kB                                                                               0.0s
 => [1/4] FROM docker.io/library/swe-agent:latest                                                                  0.0s
 => CACHED [2/4] COPY ../evaluation/evaluation.py /evaluation.py                                                   0.0s
 => CACHED [3/4] RUN pip install git+https://github.com/princeton-nlp/SWE-bench.git                                0.0s
 => CACHED [4/4] RUN pip install unidiff                                                                           0.0s
 => exporting to image                                                                                             0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:1ed08877bde203c7997e59f977bc7d39604dbf017dd6b414f918c4b7c8250de7                       0.0s
 => => naming to docker.io/library/swe-eval                                                                        0.0s

View build details: docker-desktop://dashboard/build/default/default/0800pnq5thztnswk8qhps4o3y

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview
Done with setup!
```
```
npall@Nathan MINGW64 ~/documents/swe-agent (main)
$ python run.py --model_name gpt4 \
  --data_path https://github.com/pdovhomilja/nextcrm-app/issues/30 \
  --config_file config/default_from_url.yaml
Traceback (most recent call last):
  File "C:\Users\npall\documents\swe-agent\run.py", line 13, in <module>
    from simple_parsing import parse
ModuleNotFoundError: No module named 'simple_parsing'

npall@Nathan MINGW64 ~/documents/swe-agent (main)
$ python run.py --model_name gpt4   --data_path https://github.com/pdovhomilja/nextcrm-app/issues/30   --config_file config/default_from_url.yaml
Traceback (most recent call last):
  File "C:\Users\npall\documents\swe-agent\run.py", line 13, in <module>
    from simple_parsing import parse
ModuleNotFoundError: No module named 'simple_parsing'

npall@Nathan MINGW64 ~/documents/swe-agent (main)
```

Windows 11
Anaconda
Python 3.10
Docker Desktop

**Comment by klieret** [comment]
You forgot the conda step. The dependencies are listed in `environment.yml`
